sudo: false

install: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonar/installs'

language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORGANIZATION

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: 'target/sonar-packageanalyzer-plugin-*.jar'
  skip_cleanup: true
  on:
    tags: true